name: Build and Release

on:
  push:
    branches:
      - main  # You can change this to match your main branch name
  schedule:
      - cron: '0 0 * * 1'  # Run every Monday at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    extends: .github/workflows/_steps.yaml